Use the following array

In [3]:
import numpy as np

In [1]:
## a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [4]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [5]:
np.array

<function numpy.array>

In [6]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [7]:
a >0

array([ True,  True,  True,  True, False, False, False, False, False,
       False,  True, False])

How many negative numbers are there?

In [10]:
(a<0).sum()

4

How many positive numbers are there?

In [11]:
(a>0).sum()

5

How many even positive numbers are there?

In [17]:
((a%2 == 0)&(a>0)).sum()

3

If you were to add 3 to each data point, how many positive numbers would there be?

In [21]:
a_plus3 = a + 3 

In [22]:
a_plus3

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [23]:
(a_plus3>0).sum()

10

If you squared each number, what would the new mean and standard deviation be?

In [25]:
a **2

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [31]:
#mean
np.mean((a**2))

74.0

In [32]:
#std dev
np.std((a**2))

144.0243035046516

A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering. https://www.theanalysisfactor.com/centering-and-standardizing-predictors/

to get Z score = (value - mean) / std dev

Calculate the z-score for each data point. Recall that the z-score is given by:

In [33]:
z_score = (a-(np.mean(a)))/(np.std(a))

In [34]:
z_score

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [ ]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.


In [5]:
import numpy as np
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = np.sum([a])

In [7]:
sum_of_a

55

In [8]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a =np.min([a])
min_of_a

1

In [9]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a =np.max([a])
max_of_a

10

In [11]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = np.mean((a))
mean_of_a

5.5

In [14]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = np.prod([a])
product_of_a

3628800

In [16]:
#note to self to get a list of products in a array use numpy.cumprod see example below
list_product_of_a = np.cumprod([a])
list_product_of_a

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [18]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
square_of_a = np.square([a])
square_of_a

array([[  1,   4,   9,  16,  25,  36,  49,  64,  81, 100]])

In [26]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
def odds_in_a(a):
    for num in a:
        if num % 2 != 0:
           print(num, end = " ")

In [28]:
odds_in_a(a)

1 3 5 7 9 

SETUP 2

In [ ]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])


# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)


# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)


# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

# Exercise 9 - print out the shape of the array b.

# Exercise 10 - transpose the array b.

# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

STEUP 3

## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.

# Exercise 2 - Determine the standard deviation of c.

# Exercise 3 - Determine the variance of c.

# Exercise 4 - Print out the shape of the array c

# Exercise 5 - Transpose c and print out transposed result.

# Exercise 6 - Get the dot product of the array c with c. 

# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.